<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS1.2_User enters invalid username and incorrect password to login into Orange HRM</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ce2631ec-6c3f-408f-80ed-be3b45f6e81b</testSuiteGuid>
   <testCaseLink>
      <guid>18fa8e7d-c3c6-4362-8b77-0157d71b83d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1_Login Scenarios/TC1.2_User enters invalid username to login into Orange HRM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8830410b-960a-4be2-bccf-d34301cc071a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c576c0f-b02c-41b2-a510-d9b0bbd365b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>664d4eba-8a0a-459a-99e2-100882bdffc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>459dadc9-85ea-4ca2-b3c6-fc46007a28c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1_Login Scenarios/TC1.3_User enters incorrect password to login into Orange HRM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fc0ef92-2653-4dc5-8213-15c6318eb575</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2f67a66-140f-4b0c-9fce-0200106d925e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
